### ISSUE TITLE
Add feature to official Agility plugin

### ISSUE THREAD

**Issue by robmonte** [WesleyM77/agility-pyramid-slider-block-timer#1]
Any particular reason you don't add this functionality to the Agility plugin instead of having it as a separate plugin-hub plugin? It would be nice for a lot of people! Thanks for making it!

**Comment by WesleyM77** [comment]
This was originally a PR submitted to core Runelite (see here: https://github.com/runelite/runelite/pull/14307) but Adam didn't have time to review it, so it was broken out into its own plugin. It's unfortunate, but that's how it played out. 

Thanks for the support, I'm actually blown away by how many people installed it so far without me telling anyone about it!
