### ISSUE TITLE
Top Slider Block Broken

### ISSUE THREAD

**Issue by coopermor** [WesleyM77/agility-pyramid-slider-block-timer#2]
This still works for the bottom slider block but the top slider block always shows a full filled circle. 
![image](https://github.com/WesleyM77/agility-pyramid-slider-block-timer/assets/8049699/bf516abd-fc55-4b7d-add2-b5a9d740939e)

**Comment by GarrettArhSmith** [comment]
@WesleyM77 @coopermor I fixed this in my pull request here: https://github.com/WesleyM77/agility-pyramid-slider-block-timer/pull/3

**Comment by WesleyM77** [comment]
This should be fixed by MR #3. Please give some time for this to be deployed. I can't remember how that all works. Please confirm when this is deployed and I can close this issue.

**Comment by WesleyM77** [comment]
PR to get it updated in the plugin hub here: https://github.com/runelite/plugin-hub/pull/6361

**Comment by WesleyM77** [comment]
PR accepted into plugin hub. Closing as this is now fixed, and deployed.
